### ISSUE TITLE
FIXME Count 40 / TODO Count 58

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-vc-issuer#19]
- [ ] FIXME: the SERVER_ERROR/InvalidStateError being returned is
       Commit: (021ed41) Add tests.
       File:  [test/mocha/10-api.js:108](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/test/mocha/10-api.js#L108)
       Matthew Collier commented a day ago

  - [ ] TODO: map `signer.type` to signature suite
       Commit: (4554473) Use instance issuer keys for core zcaps.
       File:  [lib/zcaps.js:205](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/zcaps.js#L205)
       Dave Longley commented 5 days ago

  - [ ] FIXME: brittle; refactor to make more robust... security also depends
       Commit: (03bc966) Start adding support for claiming users.
       File:  [lib/zcaps.js:118](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/zcaps.js#L118)
       Dave Longley commented 4 days ago

  - [ ] TODO: determine from parsing multibase key
       Commit: (03bc966) Start adding support for claiming users.
       File:  [lib/zcaps.js:85](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/zcaps.js#L85)
       Dave Longley commented 4 days ago

  - [ ] FIXME: use did-key lib instead
       Commit: (03bc966) Start adding support for claiming users.
       File:  [lib/zcaps.js:72](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/zcaps.js#L72)
       Dave Longley commented 4 days ago

  - [ ] FIXME: consider making zcap key `did:key` the controller instead
       Commit: (15a7e58) Generate zcaps for kak and hmac use.
       File:  [lib/zcaps.js:59](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/zcaps.js#L59)
       Dave Longley commented 5 days ago

  - [ ] FIXME: ensure ocapld.js checks allowedActions when verifying
       Commit: (19805dd) Implement backend user claimation code.
       File:  [lib/zcaps.js:47](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/zcaps.js#L47)
       Dave Longley commented 4 days ago

  - [ ] FIXME: use `base58-universal` instead
       Commit: (03bc966) Start adding support for claiming users.
       File:  [lib/zcaps.js:6](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/zcaps.js#L6)
       Dave Longley commented 4 days ago

  - [ ] FIXME: generate a zcap invoke/delegate key instead of kak/hmac...
       Commit: (8f1802c) Disable kak/hmac generation for accounts.
       File:  [lib/walletClient.js:26](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/walletClient.js#L26)
       Dave Longley commented 5 days ago

  - [ ] TODO: get KMS module from config
       Commit: (81cae9c) Add core files.
       File:  [lib/walletClient.js:23](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/walletClient.js#L23)
       Dave Longley commented 7 months ago

  - [ ] TODO: better handle case where zcap already exists
       Commit: (5049f4f) Handle duplicate zcap storage.
       File:  [lib/users.js:139](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/users.js#L139)
       Dave Longley commented 4 days ago

  - [ ] TODO: get did:key from account directly instead of generating
       Commit: (03bc966) Start adding support for claiming users.
       File:  [lib/users.js:92](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/users.js#L92)
       Dave Longley commented 4 days ago

  - [ ] FIXME: update reference IDs and support multiple vaults,
       Commit: (03bc966) Start adding support for claiming users.
       File:  [lib/users.js:73](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/users.js#L73)
       Dave Longley commented 4 days ago

  - [ ] FIXME: consolidate code below with _delegateToControllers in `instances.js`
       Commit: (19805dd) Implement backend user claimation code.
       File:  [lib/users.js:71](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/users.js#L71)
       Dave Longley commented 4 days ago

  - [ ] TODO: check expiration date on `meta.token.expires`
       Commit: (03bc966) Start adding support for claiming users.
       File:  [lib/users.js:29](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/users.js#L29)
       Dave Longley commented 4 days ago

  - [ ] TODO: add `invoker` and `delegator` using arrays including
       Commit: (1b7ca81) Update instance storage and APIs according to new design.
       File:  [lib/kms.js:20](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/kms.js#L20)
       Dave Longley commented 6 days ago

  - [ ] TODO: do we need to pass this or can we get it from `signer.id`?
       Commit: (81cae9c) Add core files.
       File:  [lib/issuer.js:43](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/issuer.js#L43)
       Dave Longley commented 7 months ago

  - [ ] TODO: use issuerKey.type to determine proper suite to use
       Commit: (81cae9c) Add core files.
       File:  [lib/issuer.js:41](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/issuer.js#L41)
       Dave Longley commented 7 months ago

  - [x] TODO: need to be able to get the public key ID associated with the
       Commit: (81cae9c) Add core files.
       File:  [lib/issuer.js:32](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/issuer.js#L32)
       Dave Longley commented 7 months ago

  - [ ] TODO: better handle case where zcap already exists
       Commit: (5049f4f) Handle duplicate zcap storage.
       File:  [lib/instances.js:305](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/instances.js#L305)
       Dave Longley commented 4 days ago

  - [ ] TODO: get did:key from account directly instead of generating
       Commit: (dd16742) Use more explicit zcap reference IDs.
       File:  [lib/instances.js:287](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/instances.js#L287)
       Dave Longley commented 5 days ago

  - [ ] FIXME: update reference IDs and support multiple vaults,
       Commit: (4554473) Use instance issuer keys for core zcaps.
       File:  [lib/instances.js:261](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/instances.js#L261)
       Dave Longley commented 5 days ago

  - [ ] TODO: set zcaps for every controller of the instance
       Commit: (4554473) Use instance issuer keys for core zcaps.
       File:  [lib/instances.js:255](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/instances.js#L255)
       Dave Longley commented 5 days ago

  - [ ] FIXME: add support for `kmsId` to `Hmac`
       Commit: (1b7ca81) Update instance storage and APIs according to new design.
       File:  [lib/instances.js:227](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/instances.js#L227)
       Dave Longley commented 6 days ago

  - [ ] TODO: enable getting key description from AsymmetricKey object to
       Commit: (1b7ca81) Update instance storage and APIs according to new design.
       File:  [lib/instances.js:210](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/instances.js#L210)
       Dave Longley commented 6 days ago

  - [ ] TODO: If `controller` does not match, this error is used not
       Commit: (1b7ca81) Update instance storage and APIs according to new design.
       File:  [lib/instances.js:177](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/instances.js#L177)
       Dave Longley commented 6 days ago

  - [ ] TODO: determine `public` status of information in instance
       Commit: (1b7ca81) Update instance storage and APIs according to new design.
       File:  [lib/instances.js:94](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/instances.js#L94)
       Dave Longley commented 6 days ago

  - [ ] TODO: get KMS module from config
       Commit: (1b7ca81) Update instance storage and APIs according to new design.
       File:  [lib/instances.js:25](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/instances.js#L25)
       Dave Longley commented 6 days ago

  - [ ] FIXME: use real contexts
       Commit: (81cae9c) Add core files.
       File:  [lib/http.js:256](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/http.js#L256)
       Dave Longley commented 7 months ago

  - [ ] TODO: verify VCs in VP and that they match requirements of `flow`
       Commit: (81cae9c) Add core files.
       File:  [lib/http.js:254](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/http.js#L254)
       Dave Longley commented 7 months ago

  - [ ] TODO: when verifying the VP, it includes a `challenge` that must be
       Commit: (81cae9c) Add core files.
       File:  [lib/http.js:249](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/http.js#L249)
       Dave Longley commented 7 months ago

  - [ ] TODO: verify VP
       Commit: (81cae9c) Add core files.
       File:  [lib/http.js:248](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/http.js#L248)
       Dave Longley commented 7 months ago

  - [ ] TODO: find flow in `configuration` by `flowId`
       Commit: (81cae9c) Add core files.
       File:  [lib/http.js:246](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/http.js#L246)
       Dave Longley commented 7 months ago

  - [ ] FIXME: reinstate with new `instance` design
       Commit: (1b7ca81) Update instance storage and APIs according to new design.
       File:  [lib/http.js:222](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/http.js#L222)
       Dave Longley commented 6 days ago

  - [ ] FIXME: validate body
       Commit: (c9b725d) Update HTTP API for claiming a user.
       File:  [lib/http.js:214](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/http.js#L214)
       Dave Longley commented 4 days ago

  - [ ] FIXME: remove me
       Commit: (1b7ca81) Update instance storage and APIs according to new design.
       File:  [lib/http.js:184](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/http.js#L184)
       Dave Longley commented 6 days ago

  - [ ] TODO: validate query, if any
       Commit: (1b7ca81) Update instance storage and APIs according to new design.
       File:  [lib/http.js:176](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/http.js#L176)
       Dave Longley commented 6 days ago

  - [ ] TODO: ensure capabilities are for the right thing (prevent some
       Commit: (1b7ca81) Update instance storage and APIs according to new design.
       File:  [lib/http.js:148](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/http.js#L148)
       Dave Longley commented 6 days ago

  - [ ] TODO: verify VP -- note that this will should be done by another
       Commit: (1b7ca81) Update instance storage and APIs according to new design.
       File:  [lib/http.js:145](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/http.js#L145)
       Dave Longley commented 6 days ago

  - [ ] TODO: validate VP
       Commit: (1b7ca81) Update instance storage and APIs according to new design.
       File:  [lib/http.js:130](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/http.js#L130)
       Dave Longley commented 6 days ago

  - [ ] FIXME add validation
       Commit: (9df7ae1) Implement authenticate endpoint.
       File:  [lib/http.js:36](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/http.js#L36)
       Matthew Collier commented 2 days ago

  - [ ] TODO: could be optimized via `brAccount.getAll`
       Commit: (1a4e4f9) Refactor registration and configuration code.
       File:  [lib/configurations.js:29](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/configurations.js#L29)
       Dave Longley commented 7 months ago

  - [ ] FIXME: use `Collection` instead
       Commit: (03bc966) Start adding support for claiming users.
       File:  [lib/configurations.js:10](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/configurations.js#L10)
       Dave Longley commented 4 days ago

  - [ ] FIXME: make more restrictive, support `did:key` and `did:v1`
       Commit: (03bc966) Start adding support for claiming users.
       File:  [lib/Collection.js:185](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/Collection.js#L185)
       Dave Longley commented 4 days ago

  - [ ] TODO: will need to be able to get all
       Commit: (03bc966) Start adding support for claiming users.
       File:  [lib/Collection.js:143](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/Collection.js#L143)
       Dave Longley commented 4 days ago

  - [ ] TODO: index based on supported credential types for the instance
       Commit: (03bc966) Start adding support for claiming users.
       File:  [lib/Collection.js:142](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/Collection.js#L142)
       Dave Longley commented 4 days ago

  - [ ] FIXME: make sure compound indexes work
       Commit: (0080077) Disable compound unique index.
       File:  [lib/Collection.js:138](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/Collection.js#L138)
       Dave Longley commented 4 days ago

  - [ ] TODO: base this off of bedrock.config
       Commit: (03bc966) Start adding support for claiming users.
       File:  [lib/Collection.js:131](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/Collection.js#L131)
       Dave Longley commented 4 days ago

  - [ ] FIXME: bikeshed name
       Commit: (03bc966) Start adding support for claiming users.
       File:  [lib/Collection.js:24](https://github.com/digitalbazaar/bedrock-vc-issuer/blob/master/lib/Collection.js#L24)
       Dave Longley commented 4 days ago

       FIXME Count         40
       TODO Count          58
       Oldest Comment      7 months ago
       Oldest Commenter    Dave Longley
       Oldest Comment      TODO: get KMS module from config

**Comment by dlongley** [comment]
Closing as stale.
